import Head from 'next/head';
import Image from 'next/image' //used for images (see README.md)
import { Bungee_Hairline } from '@next/font/google';
import styles from '@/styles/Home.module.css';

import Window from './components/Window';

//Fonts
const BungeeHairline  = Bungee_Hairline({weight: "400"});

const logs = [
  {
    time: "04:06:23",
    message: "A QR Code has been generated"
  },
  {
    time: "04:06:30",
    message: "Waiting for PAYER to scan code..."
  },
]

export default function Home() {
  return (
    <>
      <Head>
        <title>VRP Testing Suite</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={BungeeHairline.className}>VRP Testing Suite</h1>
        <div id={styles.WindowBoard}>
          <Window active={false} title="POS" loadedContent={
            <Image src="/rr-qr.jpg" alt="QR Code"
              className={styles.vercelLogo}
              width={300}
              height={300}
              priority />
          } />
          <Window active={true} title="LOGS" loadedText={logs} />
          <Window active={false} title="PAYER" />
        </div>
      </main>
    </>
  )
}
