import Head from 'next/head';
//import Image from 'next/image'
import { Bungee_Hairline } from '@next/font/google';
import { Cutive_Mono } from '@next/font/google';
import { Alumni_Sans  } from '@next/font/google';
import styles from '@/styles/Home.module.css';

//Fonts
const BungeeHairline = Bungee_Hairline({weight: "400"});
const CutiveMono = Cutive_Mono({weight: "400"});
const AlumniSans = Alumni_Sans({weight: "400"});

export default function Home() {
  return (
    <>
      <Head>
        <title>VRP Testing Suite</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={BungeeHairline.className}>VRP Testing Suite</h1>
        <div id={styles.WindowBoard}>
          <div className={`${styles.window}`}>
            <div className={styles.top}>
              <h3 className={AlumniSans.className}>POS</h3>
            </div>
            <div className={styles.bottom}>
              <p className={CutiveMono.className}>Lorem ipsum dolor sit amet consectetur adipisicing elit. Quibusdam, quasi?</p>
            </div>
          </div>
          <div className={`${styles.thirteen} ${styles.window}`}>
            <div className={styles.top}>
              <h3 className={AlumniSans.className}>LOGS</h3>
            </div>
            <div className={styles.bottom}>
              <p className={CutiveMono.className}>Lorem ipsum dolor sit amet consectetur adipisicing elit. Quibusdam, quasi?</p>
            </div>
          </div>
          <div className={`${styles.window}`}>
            <div className={styles.top}>
              <h3 className={AlumniSans.className}>PAYER</h3>
            </div>
            <div className={styles.bottom}>
              <p className={CutiveMono.className}>Lorem ipsum dolor sit amet consectetur adipisicing elit. Quibusdam, quasi?</p>
            </div>
          </div>
        </div>
      </main>
    </>
  )
}
